name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/sellmmo/sellermmo
            git reset --hard
            git pull origin main
            docker exec sellmmo-app php artisan migrate --force
            docker exec sellmmo-app php artisan optimize:clear
            docker restart sellmmo-queue
            docker restart sellmmo-scheduler
